NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Controllers/WeeklyExercisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NOVA_VERZIJA_IT.Models;

namespace NOVA_VERZIJA_IT.Controllers
{
    public class WeeklyExercisesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //dodadeni 2ta metoda
        public ActionResult AddExercise(int workoutPlanId)
        {
            ViewBag.ExerciseID = new SelectList(db.Exercises, "ID", "Name");
            var weeklyExercise = new WeeklyExercise { WorkoutPlanID = workoutPlanId };

            return View(weeklyExercise);
        }

        // POST: WeeklyExercises/AddExercise
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddExercise([Bind(Include = "ID,DayOfWeek,Sets,Reps,ExerciseID,WorkoutPlanID")] WeeklyExercise weeklyExercise)
        {
            if (ModelState.IsValid)
            {
                db.WeeklyExercises.Add(weeklyExercise);
                db.SaveChanges();
                return RedirectToAction("Details", "WorkoutPlans", new { id = weeklyExercise.WorkoutPlanID });
            }

            ViewBag.ExerciseID = new SelectList(db.Exercises, "ID", "Name", weeklyExercise.Exercise);
            return View(weeklyExercise);
        }


        // GET: WeeklyExercises
        public ActionResult Index()
        {
            var weeklyExercises = db.WeeklyExercises.Include(w => w.Exercise);
            return View(weeklyExercises.ToList());
        }

        // GET: WeeklyExercises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WeeklyExercise weeklyExercise = db.WeeklyExercises.Find(id);
            if (weeklyExercise == null)
            {
                return HttpNotFound();
            }
            return View(weeklyExercise);
        }

        // GET: WeeklyExercises/Create
        public ActionResult Create()
        {
            ViewBag.ExerciseId = new SelectList(db.Exercises, "ID", "Name");
            return View();
        }

        // POST: WeeklyExercises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ExerciseId,DayOfWeek,Sets,Reps")] WeeklyExercise weeklyExercise)
        {
            if (ModelState.IsValid)
            {
                db.WeeklyExercises.Add(weeklyExercise);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ExerciseId = new SelectList(db.Exercises, "ID", "Name", weeklyExercise.ExerciseId);
            return View(weeklyExercise);
        }

        // GET: WeeklyExercises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WeeklyExercise weeklyExercise = db.WeeklyExercises.Find(id);
            if (weeklyExercise == null)
            {
                return HttpNotFound();
            }
            ViewBag.ExerciseId = new SelectList(db.Exercises, "ID", "Name", weeklyExercise.ExerciseId);
            return View(weeklyExercise);
        }

        // POST: WeeklyExercises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ExerciseId,DayOfWeek,Sets,Reps")] WeeklyExercise weeklyExercise)
        {
            if (ModelState.IsValid)
            {
                db.Entry(weeklyExercise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ExerciseId = new SelectList(db.Exercises, "ID", "Name", weeklyExercise.ExerciseId);
            return View(weeklyExercise);
        }

        // GET: WeeklyExercises/Delete/5
        public ActionResult Delete(int id)
        {
            var weeklyExercise = db.WeeklyExercises.Find(id);

            if (weeklyExercise == null)
            {
                return HttpNotFound();
            }

            return View(weeklyExercise);
        }

        // POST: WeeklyExercises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var weeklyExercise = db.WeeklyExercises.Find(id);

            if (weeklyExercise != null)
            {

                db.WeeklyExercises.Remove(weeklyExercise);
                db.SaveChanges();
            }
            return RedirectToAction("Details", "WorkoutPlans", new {id = weeklyExercise.WorkoutPlanID});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/WeeklyExercises/AddExercise.cshtml
@model NOVA_VERZIJA_IT.Models.WeeklyExercise
@{
    ViewBag.Title = "AddExercise";
}

<h2 class="text-center">Add an exercise</h2>

<div class="container">

    @using (Html.BeginForm("AddExercise", "WeeklyExercises", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.HiddenFor(model => model.WorkoutPlanID)

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DayOfWeek, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DayOfWeek, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseId, "Exercise", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExerciseID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExerciseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sets, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Sets, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sets, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Reps, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Reps, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Exercise" class="btn btn-default" />
            </div>
        </div>

    }

</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/WeeklyExercises/Create.cshtml
@model NOVA_VERZIJA_IT.Models.WeeklyExercise

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WeeklyExercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseId, "ExerciseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExerciseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExerciseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayOfWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayOfWeek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sets, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sets, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sets, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reps, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reps, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/WeeklyExercises/Delete.cshtml
@model NOVA_VERZIJA_IT.Models.WeeklyExercise

@{
    ViewBag.Title = "Delete";
}

<div class="container">

    <h2 class="text-center">Delete Exercise</h2>

    <!--bootbox da stavam tuka -->
    <div class="alert alert-warning">

        <h4>Are you sure you want to delete this exercise</h4>
        <p>@Model.Exercise.Name - @Model.Sets sets, @Model.Reps reps</p>

        @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken();
                <input type="submit" value="Delete" class="btn btn-danger"/>
                <a href="@Url.Action("Details", new {id = Model.WorkoutPlanID})" class="btn btn-secondary">Cancel</a>
            }

    </div>

</div>

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/WeeklyExercises/Details.cshtml
@model NOVA_VERZIJA_IT.Models.WeeklyExercise

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WeeklyExercise</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Exercise.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exercise.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DayOfWeek)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DayOfWeek)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reps)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reps)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/WeeklyExercises/Edit.cshtml
@model NOVA_VERZIJA_IT.Models.WeeklyExercise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WeeklyExercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ExerciseId, "ExerciseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ExerciseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExerciseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DayOfWeek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DayOfWeek, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DayOfWeek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sets, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sets, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sets, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reps, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Reps, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reps, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/WeeklyExercises/Index.cshtml
@model IEnumerable<NOVA_VERZIJA_IT.Models.WeeklyExercise>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Exercise.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DayOfWeek)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sets)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reps)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Exercise.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DayOfWeek)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sets)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Reps)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>