NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Controllers/ExercisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NOVA_VERZIJA_IT.Models;

namespace NOVA_VERZIJA_IT.Controllers
{
    public class ExercisesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Exercises

        //filter by muscle group AND filter both at the same time 
        /*
      
         * public ActionResult Index(int page = 1, string search = "", string category = "", List<string> muscleGroups = null)
        {
            int pageSize = 9;

            var exerciseQuery = db.Exercises.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                exerciseQuery = exerciseQuery.Where(e => e.Name.Contains(search));
            }

            if (!string.IsNullOrEmpty(category))
            {
                exerciseQuery = exerciseQuery.Where(e => e.Category == category);
            }


            var exercises = exerciseQuery.ToList();


            if (muscleGroups != null && muscleGroups.Any())
            {
                exercises = exercises.Where(e => e.muscleGroups != null && e.muscleGroups.Any(mg => muscleGroups.Contains(mg))).ToList();
            }

            var paginated_exercises = exercises
                              .OrderBy(e => e.Category) // or another sorting criterion
                              .Skip((page - 1) * pageSize)
                              .Take(pageSize)
                              .ToList();

            var totalExercises = exercises.Count();

            var totalPages = (int)Math.Ceiling((double)totalExercises / pageSize);

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentCategory = category;
            ViewBag.CurrentMuscleGroups = muscleGroups;

            return View(paginated_exercises);
        }
        */
        
        

        //FILTER BY CATEGORY
        public ActionResult Index(int page = 1, string search = "", string category = "", List<string> muscleGroups = null)
        {
            int pageSize = 9;

            var exerciseQuery = db.Exercises.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                exerciseQuery = exerciseQuery.Where(e => e.Name.Contains(search));
            }

            if (!string.IsNullOrEmpty(category))
            {
                exerciseQuery = exerciseQuery.Where(e => e.Category == category);
            }

            if (muscleGroups != null && muscleGroups.Any())
            {
                // Filters exercises where any of their muscle groups match any in the selected list
                exerciseQuery = exerciseQuery.Where(e => e.muscleGroups.Any(mg => muscleGroups.Contains(mg)));
            }


            //do tuka

            var exercises = db.Exercises
                               .Where(e => (string.IsNullOrEmpty(search) || e.Name.Contains(search)) && (string.IsNullOrEmpty(category) || e.Category == category))
                               .OrderBy(e => e.Category) // or another sorting criterion
                               .Skip((page - 1) * pageSize)
                               .Take(pageSize)
                               .ToList();

            var totalExercises = db.Exercises
                           .Count(e => (string.IsNullOrEmpty(search) || e.Name.Contains(search)) &&
                                       (string.IsNullOrEmpty(category) || e.Category == category));

            var totalPages = (int)Math.Ceiling((double)totalExercises / pageSize);

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentSearch = search;
            ViewBag.CurrentCategory = category;
            ViewBag.CurrentMuscleGroups = muscleGroups;

            return View(exercises);
        }
        


        // GET: Exercises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            return View(exercise);
        }

        // GET: Exercises/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Exercises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Category,Description,VideoUrl,muscleGroups")] Exercise exercise)
        {
            if (ModelState.IsValid)
            {
               
                db.Exercises.Add(exercise);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(exercise);
        }

        // GET: Exercises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            return View(exercise);
        }

        // POST: Exercises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Category,Description,VideoUrl,muscleGroups")] Exercise exercise)
        {
            if (ModelState.IsValid)
            {
                ViewBag.ExerciseName = exercise.Name;

                db.Entry(exercise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exercise);
        }

        // GET: Exercises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            return View(exercise);
        }

        // POST: Exercises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Exercise exercise = db.Exercises.Find(id);

           
                db.Exercises.Remove(exercise);
                db.SaveChanges();
            

            return RedirectToAction("Index");
        }


        public ActionResult addNewWorkout(int id)
        {
            /*
            var model = new WorkoutExercisePlans();

            model.exerciseID = id;
            model.Exercise = db.Exercises.Find(id);
            model.WorkoutPlans = db.WorkoutPlans.ToList();

            return View(model);
            */

        var exercise = db.Exercises.Find(id);

            if (exercise == null)
            {
                return HttpNotFound();
            }

            ViewBag.ExerciseName = exercise.Name;


            var model = new WorkoutExercisePlans
            {
                      exerciseID = exercise.ID,
                   // exerciseID = id,
                    WorkoutPlans = db.WorkoutPlans.Select(wp => new SelectListItem
                {
                    Value = wp.ID.ToString(),
                    Text = wp.Title
                }).ToList()
            };
            
            return View(model);

        }



        //[HttpPost]
        //public ActionResult addNewWorkout(WorkoutExercisePlans model)
        //{
        //    /*
        //    var workoutPlan = db.WorkoutPlans.Find(model.workoutPlanID);
        //    var exercise = db.Exercises.Find(model.exerciseID);

        //    exercise.WorkoutPlans.Add(workoutPlan);
        //    db.SaveChanges();

        //    return View("Details", exercise);
        //    */

        //    var exercise = db.Exercises.Find(model.exerciseID);

        //    if (exercise != null)
        //    {
        //        // Clear existing workout plans
        //        exercise.WorkoutPlans.Clear();

        //        // Add new workout plans
        //        foreach (var planId in model.selectedWorkoutPlanIDs)
        //        {
        //            var plan = db.WorkoutPlans.Find(planId);
        //            if (plan != null)
        //            {
        //                exercise.WorkoutPlans.Add(plan);

        //            }
        //        }

        //        db.SaveChanges();
        //    }

        //    return RedirectToAction("Index");

        //}


        [HttpPost]
        public ActionResult addNewWorkout(WorkoutExercisePlans model)
        {
            var exercise = db.Exercises.Find(model.exerciseID);

            if (exercise != null)
            {
                foreach (var planId in model.selectedWorkoutPlanIDs)
                {
                    var plan = db.WorkoutPlans.Find(planId);

                    if (plan != null)
                    {
                        exercise.WorkoutPlans.Add(plan);

                        if (!string.IsNullOrEmpty(model.DayOfWeek))
                        {
                            plan.WeeklyExercises.Add(new WeeklyExercise
                            {
                                ExerciseId = exercise.ID,

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Controllers/WorkoutPlansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NOVA_VERZIJA_IT.Models;

namespace NOVA_VERZIJA_IT.Controllers
{
    public class WorkoutPlansController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: WorkoutPlans
        public ActionResult Index()
        {
            return View(db.WorkoutPlans.ToList());
        }

        // GET: WorkoutPlans/Details/5
        

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutPlan workoutPlan = db.WorkoutPlans.Find(id);
            if (workoutPlan == null)
            {
                return HttpNotFound();
            }
            return View(workoutPlan);
        }

        // GET: WorkoutPlans/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorkoutPlans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Description,ImageURL")] WorkoutPlan workoutPlan)
        {
            if (ModelState.IsValid)
            {
                db.WorkoutPlans.Add(workoutPlan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(workoutPlan);
        }

        // GET: WorkoutPlans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutPlan workoutPlan = db.WorkoutPlans.Find(id);
            if (workoutPlan == null)
            {
                return HttpNotFound();
            }
            return View(workoutPlan);
        }

        // POST: WorkoutPlans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Description,ImageURL")] WorkoutPlan workoutPlan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workoutPlan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workoutPlan);
        }

        // GET: WorkoutPlans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutPlan workoutPlan = db.WorkoutPlans.Find(id);
            if (workoutPlan == null)
            {
                return HttpNotFound();
            }
            return View(workoutPlan);
        }

        // POST: WorkoutPlans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkoutPlan workoutPlan = db.WorkoutPlans.Find(id);
            db.WorkoutPlans.Remove(workoutPlan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //ne treba metodov
        [HttpPost]
        public ActionResult AddExerciseToDayOfWeek(int workoutPlanId, string dayOfWeek, string name, string description)
        {
            var exercise = new Exercise
            {
                Name = name,
                DayOfWeek = dayOfWeek,
                Description = description
            };

            db.Exercises.Add(exercise);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = workoutPlanId });

        }
        

        

        public ActionResult addNewExercise(int id)
        {
            var model = new WorkoutPlanExercises();

            model.workoutPlanID = id;
            model.WorkoutPlan = db.WorkoutPlans.Find(id);
            model.Exercises = db.Exercises.ToList();

            return View(model);

        }

        [HttpPost]
        public ActionResult addNewExercise(WorkoutPlanExercises model)
        {
            

            var workoutPlan = db.WorkoutPlans.Find(model.workoutPlanID);
            var exercise = db.Exercises.Find(model.exerciseID);

            workoutPlan.Exercises.Add(exercise);
            db.SaveChanges();

            return View("Details", workoutPlan);
            
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!--Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!--Bootstrap JavaScript-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css">

    @{
        string navbarClass = User.IsInRole("Admin") ? "navbar-admin" : "navbar-user";
    }

    <style>
        .bg-dark {
            background-color: #000000 !important;
        }

        .navbar-user .navbar-nav .nav-link {
            color: white;
            padding: 0 15px;
            font-size: 16px;
        }

        .navbar-admin .navbar-nav .nav-link {
            color: white;
            padding: 0 15px;
            font-size: 14px;
        }

        .navbar-dark .navbar-nav .nav-link:hover {
            color: coral;
        }

        .navbar {
            padding: 0 !important;
        }

        .login {
            margin-right: -100px;
            font-size: 15px;
        }

        .navbar-brand img {
            width: 100px;
            height: 60px;
        }

        .navbar-collapse {
            justify-content: space-between;
        }

        .navbar-nav {
            display: flex;
            flex-wrap: wrap;
        }

        .nav-item {
            flex: 0 1 auto;
        }

        ul.navbar-nav.m1-auto li {
            padding-left: 30px;
        }

        /* Footer */
        .footer {
            background-color: #343a40;
            color: #fff;
            padding: 20px 0; /* Reduced padding */
            font-size: 14px; /* Smaller font size */
            margin-top: 30px;
        }

        .footer-logo {
            max-width: 180px;
            margin-bottom: 5px;
            margin-left: 100px;
        }

        .footer h5 {
            margin-bottom: 10px; /* Reduced margin */
            color: #fff;
            font-size: 14px; /* Smaller font size */
            text-transform: uppercase;
        }

        .footer ul {
            padding: 0;
            list-style: none;
        }

            .footer ul li {
                margin-bottom: 5px; /* Reduced margin */
            }

                .footer ul li a {
                    color: #aaa;
                    text-decoration: none;
                }

                    .footer ul li a:hover {
                        color: #fff;
                    }

        .social-media {
            display: flex;
            align-items: center;
            margin-top: 10px; /* Reduced margin */
        }

            .social-media i {
                font-size: 18px; /* Smaller icon size */
                margin-right: 5px; /* Reduced margin */
                color: #007bff;
                padding: 8px;
            }

            .social-media a {
                color: #007bff;
                text-decoration: none;
            }

                .social-media a:hover {
                    color: #0056b3;
                }

        .footer .contact-info p {
            margin: 3px 0; /* Reduced margin */
        }

        .footer .contact-info i {
            margin-right: 3px; /* Reduced margin */
        }

        .footer-bottom {
            text-align: center;
            margin-top: 10px; /* Reduced margin */
            border-top: 1px solid #4e555b;
            padding-top: 10px; /* Reduced padding */
        }
    </style>
</head>
<body>

        <nav class="navbar navbar-expand-sm navbar-dark bg-dark @navbarClass">
            <div class="container">
                <a class="navbar-brand" href="/Home/Index">
                    <img src="~/images/fitforge-high-resolution-logo-white.png" width="120" height="90" />
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse fs-6" id="navbarNav">
                    <ul class="navbar-nav m1-auto ">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "WorkoutPlans")">
                                    <i class="fas fa-dumbbell"></i> Workout Plan
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "ActivityLogs")">
                                    <i class="fas fa-chart-line"></i> My Progress
                                </a>
                            </li>
                            <li id="dietAndNutritionLink" class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "DietAndNutrition")">
                                    <i  class="fas fa-utensils"></i> Diet and Nutrition
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Exercises")">
                                    <i class="fas fa-running"></i> Exercises
                                </a>
                            </li>

                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("AddUserToRole", "Account")">
                                        <i class="fas fa-users-cog"></i> Manage Roles
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("ListUsers", "Admin")">
                                        <i class="fas fa-users"></i> Users
                                    </a>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <div class="login">
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <img src="~/images/logo-no-background.png" alt="Logo" class="footer-logo" />
                </div>
                <div class="col-md-2">
                    <h5>Useful Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="https://myfitnesspal.com">myfitnesspal.com</a></li>
                        <li><a href="https://muscleandstrength.com">muscleandstrength.com</a></li>
                        <li><a href="https://bodybuilding.com">bodybuilding.com</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Contact</h5>
                    <div class="contact-info">
                        <p><i class="bi bi-geo-alt"></i> Skopje, Macedonia</p>
                        <p><i class="bi bi-telephone"></i> +38970305025</p>
                        <p><i class="bi bi-envelope"></i> <a href="mailto:fitforge10@gmail.com">fitforge10@gmail.com</a></p>
                    </div>
                </div>
                <div class="col-md-3">
                    <h5>Follow Us</h5>
                    <div class="social-media">
                        <a href="https://www.facebook.com/fitforge.mk"><i class="bi bi-facebook"></i></a>
                        <a href="https://www.instagram.com/fitforge.mk/"><i class="bi bi-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12 footer-bottom">
                    <p>&copy; 2024 FitForge. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>