NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Models/FitnessUser.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NOVA_VERZIJA_IT.Models
{
    public class FitnessUser 
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "Contact Number")]
        public string contactNumber { get; set; }

        [Display(Name = "Profile Image")]
        public IFormFile Image { get; set; }

        [Display(Name = "Date of Birth")]
        public DateTime dateOfBirth { get; set; }

        [Display(Name = "Membership Created")]
        public DateTime membershipCreated { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }


        //dodadeno od RegisterViewModel
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }


        public virtual ICollection<WorkoutPlan> WorkoutPlans { get; set; }

        public FitnessUser()
        {
            WorkoutPlans = new List<WorkoutPlan>();
        }
    }
}

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Controllers/FitnessUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NOVA_VERZIJA_IT.Models;

namespace NOVA_VERZIJA_IT.Controllers
{
    public class FitnessUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FitnessUsers
        public ActionResult Index()
        {
            return View(db.FitnessUsers.ToList());
        }

        // GET: FitnessUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitnessUser fitnessUser = db.FitnessUsers.Find(id);
            if (fitnessUser == null)
            {
                return HttpNotFound();
            }
            return View(fitnessUser);
        }

        // GET: FitnessUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FitnessUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FullName,Address,contactNumber,image,dateOfBirth,membershipCreated,Height,Weight")] FitnessUser fitnessUser)
        {
            if (ModelState.IsValid)
            {
                db.FitnessUsers.Add(fitnessUser);
                db.SaveChanges();
                return RedirectToAction("ListUsers");
            }

            return View(fitnessUser);
        }

        // GET: FitnessUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitnessUser fitnessUser = db.FitnessUsers.Find(id);
            if (fitnessUser == null)
            {
                return HttpNotFound();
            }
            return View(fitnessUser);
        }

        // POST: FitnessUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FullName,Address,contactNumber,image,dateOfBirth,membershipCreated,Height,Weight")] FitnessUser fitnessUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fitnessUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fitnessUser);
        }

        // GET: FitnessUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FitnessUser fitnessUser = db.FitnessUsers.Find(id);
            if (fitnessUser == null)
            {
                return HttpNotFound();
            }
            return View(fitnessUser);
        }

        // POST: FitnessUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FitnessUser fitnessUser = db.FitnessUsers.Find(id);
            db.FitnessUsers.Remove(fitnessUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult addNewWorkoutPlan(int id)
        {
            var model = new FitnessUserWorkoutsPlans();

            model.FitnessID = id;
            model.FitnessUser = db.FitnessUsers.Find(id);
            model.WorkoutPlans = db.WorkoutPlans.ToList();

            return View(model);

        }

        [HttpPost]

        public ActionResult addNewWorkoutPlan(FitnessUserWorkoutsPlans model)
        {
            var user = db.FitnessUsers.Find(model.FitnessID);
            var workout = db.WorkoutPlans.Find(model.WPID);

            user.WorkoutPlans.Add(workout);
            db.SaveChanges();

            return View("Details", user);
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/FitnessUsers/Create.cshtml
@model NOVA_VERZIJA_IT.Models.FitnessUser

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>FitnessUser</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.contactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.contactNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.contactNumber, "", new { @class = "text-danger" })
        </div>
    </div>      
               

            <div class="form-group">
                @Html.LabelFor(model => model.dateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.dateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.membershipCreated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.membershipCreated, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.membershipCreated, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/FitnessUsers/Delete.cshtml
@model NOVA_VERZIJA_IT.Models.FitnessUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FitnessUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.membershipCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.membershipCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/FitnessUsers/Details.cshtml
@model NOVA_VERZIJA_IT.Models.FitnessUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FitnessUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.membershipCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.membershipCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

    </dl>
</div>

<div>
    Workouts:
    <ul>
        @foreach (var item in Model.WorkoutPlans)
        {
            <li>
                @item.Title
            </li>


        }

    </ul>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/FitnessUsers/Edit.cshtml
@model NOVA_VERZIJA_IT.Models.FitnessUser

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FitnessUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.membershipCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.membershipCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.membershipCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/FitnessUsers/Index.cshtml
@model IEnumerable<NOVA_VERZIJA_IT.Models.FitnessUser>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contactNumber)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.membershipCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contactNumber)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.dateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.membershipCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID }) |
            @Html.ActionLink("Add New", "addNewWorkoutPlan", new { id = item.ID })
        </td>
    </tr>
}

</table>

NOVA_VERZIJA_IT/NOVA_VERZIJA_IT/Views/FitnessUsers/addNewWorkoutPlan.cshtml
@model NOVA_VERZIJA_IT.Models.FitnessUserWorkoutsPlans 
@{
    ViewBag.Title = "addNewWorkoutPlan";
}

<h2>addNewWorkoutPlan</h2>

@using (Html.BeginForm("addNewWorkoutPlan", "FitnessUsers"))
{
    <div>
        @Html.HiddenFor(m => m.FitnessID)
        @Html.DropDownListFor(m => m.WPID,
       new SelectList(Model.WorkoutPlans, "ID", "Title"))

        <br />
        <button>Save</button>
    </div>
}